-- 用户表
CREATE TABLE SMILE_USER
(
    USER_ID     VARCHAR(255) PRIMARY KEY NOT NULL,
    USERNAME    VARCHAR(255),
    PASSWORD    VARCHAR(255),
    CREATE_TIME VARCHAR(20)
);

-- 文档信息表
CREATE TABLE SMILE_DOCUMENT
(
    DOC_ID        VARCHAR(255) PRIMARY KEY NOT NULL,
    USER_ID       VARCHAR(255),
    DOCUMENT_TYPE VARCHAR(10),
    DOCUMENT_PATH VARCHAR(255),
    DOCUMENT_KEY  VARCHAR(255),
    CREATE_TIME   VARCHAR(20)
);

-- 回收站表
CREATE TABLE SMILE_RECYCLE_BIN (
    BIN_ID VARCHAR(255) PRIMARY KEY NOT NULL,
    CREATE_TIME VARCHAR(20),
    DOC_ID VARCHAR(255),
    USER_ID VARCHAR(255)
);