-- 用户表
CREATE TABLE SMILE_USER
(
    USER_ID     VARCHAR(255),
    USERNAME    VARCHAR(255),
    PASSWORD    VARCHAR(255),
    CREATE_TIME VARCHAR(20)
);

-- 文档信息表
CREATE TABLE SMILE_DOCUMENT
(
    DOC_ID        VARCHAR(255),
    USER_ID       VARCHAR(255),
    DOCUMENT_TYPE VARCHAR(10),
    DOCUMENT_PATH VARCHAR(255),
    DOCUMENT_KEY  VARCHAR(255),
    CREATE_TIME   VARCHAR(20)
);