spring:
  # 热部署开启
  devtools:
    restart:
      enabled: true
  # 文件上传大小限制
  servlet:
    multipart:
      # 配置文件上传的限制
      enabled: true
      # 单个文件大小限制
      max-file-size: 10MB
      # 设置总上传数据大小
      max-request-size: 100MB
  jpa:
    show-sql: false
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: smile
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://101.34.213.93:15432/smile?currentSchema=smile
    username: ENC(dZr4YbSD/4XjXkj2xH1QbQ==)
    password: ENC(cUnSEC7yDySbg3KyH7vZbzmCzaCNn7Hs)
    driver-class-name: org.postgresql.Driver

jasypt:
  encryptor:
    password: zhoushs@jasypt
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# 静态资源访问配置
resources:
  static:
    pattern: /static/**
    location: classpath:/static/
  files:
    pattern: /files/**
    location: /app/data/smile_office/files/

# minio配置
minio:
  url: http://101.34.213.93:9010
  accessKey: minio
  secretKey: passw0rd